_wandb:
    value:
        cli_version: 0.28.1
        e:
            gza738nr6p9ov7lcrlq7uyzvj4lhmn33:
                args:
                    - --id
                    - sa
                    - --task-conf
                    - altruistic_10
                    - --env-conf
                    - clusters_eta
                    - --alg-conf
                    - config1
                    - --net
                    - saint_arnoult
                    - --env-seed
                    - "42"
                    - --torch-seed
                    - "42"
                codePath: scripts\qmix_torchrl.py
                codePathLocal: qmix_torchrl.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "254345736192"
                        used: "243944079360"
                email: stasscpl@gmail.com
                executable: C:\Users\Stanisław\Desktop\AIntern\URB\venv\Scripts\python.exe
                git:
                    commit: 4e9c1098685c074b396fd5f362cdd42325bb1bae
                    remote: https://github.com/COeXISTENCE-PROJECT/URB.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-29bb3c6b-57d9-d963-9521-2e2a1894e808
                host: DESKTOP-4HBJ14G
                memory:
                    total: "16789004288"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Stanisław\Desktop\AIntern\URB\scripts\qmix_torchrl.py
                python: CPython 3.13.8
                root: C:\Users\Stanisław\Desktop\AIntern\URB\scripts
                startedAt: "2026-07-30T13:13:40.816558Z"
                writerId: gza738nr6p9ov7lcrlq7uyzvj4lhmn33
        m: []
        python_version: 3.13.8
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 15
                - 16
            "4": 3.13.8
            "5": 0.28.1
            "8":
                - 3
            "12": 0.28.1
            "13": windows-amd64
agent_frames_per_batch:
    value: 20
alg_config:
    value: config1
algorithm:
    value: qmix_torchrl
av_behavior:
    value: altruistic
env_config:
    value: clusters_eta
env_seed:
    value: 42
eps_greedy_end:
    value: 0.1
eps_greedy_init:
    value: 1
exploration_fraction:
    value: 0.6
gamma:
    value: 0.95
human_alpha:
    value: 0.2
human_beta:
    value: -1.5
human_beta_randomness:
    value: 0.1
human_deterministic:
    value: false
human_learning_episodes:
    value: 300
human_model:
    value: gawron
lr:
    value: 0.0004
max_grad_norm:
    value: 1
memory_size:
    value: 30000
minibatch_size:
    value: 256
mixing_embed_dim:
    value: 192
mlp_cells:
    value: 256
mlp_depth:
    value: 4
n_iters:
    value: 200
network:
    value: saint_arnoult
num_agents:
    value: 222
num_epochs:
    value: 2
num_machines:
    value: 22
num_samples:
    value: 10
number_of_paths:
    value: 4
observations:
    value: trip_info_eta
od_embedding_dim:
    value: 8
path_gen_beta:
    value: -5
plot_choices:
    value: basic
plot_every:
    value: 50
ratio_machines:
    value: 0.1
save_every:
    value: 5
script:
    value: scripts/qmix_torchrl.py
share_params_agent:
    value: true
should_humans_adapt:
    value: false
smooth_by:
    value: 10
task_config:
    value: altruistic_10
tau:
    value: 0.01
test_eps:
    value: 100
torch_seed:
    value: 42
use_clustered_routes:
    value: true
